### ISSUE TITLE
Add https to nerdstein.net

### ISSUE THREAD

**Issue by shaal** [nerdstein/nerdstein-drupal8#34]
Opening http://nerdstein.net in a modern browser displays an error icon because the connection is not secured.
Implement https://letsencrypt.org to resolve this issue.

**Comment by shaal** [comment]
I never tried this before, but perhaps this service would be easier to implement?
https://certbot.eff.org/about/

**Comment by nerdstein** [comment]
I've used it a good bit on simplytest. I think a lot of the Edge services offer SSL. Maybe if we implement CloudFlare that will cover us. What do you think?

**Comment by nerdstein** [comment]
I used CloudFlare's native SSL
