### ISSUE TITLE
Utilize free CDN

### ISSUE THREAD

**Issue by shaal** [nerdstein/nerdstein-drupal8#36]
Cloudflare offers free CDN for personal blogs.

Current performance can be improved by adding CDN.
https://www.webpagetest.org/performance_optimization.php?test=201230_DiHK_1c1c3618db57273eeebc5a9f5cb3436e&run=2#cache_static_content

Cloudflare free CDN plan: https://www.cloudflare.com/plans/#free-modal

**Comment by nerdstein** [comment]
I enabled that. Thank you
